version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  monitor-net:

services:
  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d' # Default retention: 15 days - change as needed
      - '--web.enable-lifecycle' # Allows hot reloads via API call
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: prom/pushgateway:v1.8.0
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitor-net
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Default admin user
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default admin password - CHANGE THIS!
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
